/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PaketRentalController;
import java.awt.Color;
import model.PaketRental;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class FormPaketRental extends javax.swing.JFrame {

    PaketRentalController controller = new PaketRentalController();

    private int idPaketTerpilih = 0;
    
    /**
     * Creates new form FormPaketRental
     */
    
    public void tampilTabel(){

        tblPaketRental.setModel(controller.tampilData());

    }
    
    public FormPaketRental() {
        initComponents();
        
        btnTambah.setBackground(new Color(0,153,255));
        btnTambah.setForeground(Color.WHITE);

        btnEdit.setBackground(new Color(0,153,255));
        btnEdit.setForeground(Color.WHITE);

        btnReset.setBackground(new Color(0,153,255));
        btnReset.setForeground(Color.WHITE);
        
        btnKembali.setBackground(new Color(0,153,255));
        btnKembali.setForeground(Color.WHITE);
        
        btnHapus.setBackground(new Color(220,53,69));
        btnHapus.setForeground(Color.WHITE);
        
        tampilTabel();
    }
    
    public void resetForm(){

        txtNamaPaket.setText("");

        txtDurasi.setText("");

        txtHarga.setText("");

        idPaketTerpilih = 0;

        tblPaketRental.clearSelection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNama = new javax.swing.JLabel();
        lblDurasi = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        txtNamaPaket = new javax.swing.JTextField();
        txtDurasi = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaketRental = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setText("Nama Paket :");

        lblDurasi.setText("Durasi Jam :");

        lblHarga.setText("Harga Paket : ");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblPaketRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Paket", "Durasi", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPaketRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaketRentalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaketRental);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnTambah)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEdit))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHarga)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDurasi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNama)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKembali)
                        .addGap(57, 57, 57)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDurasi)
                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if(txtNamaPaket.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(this, "Nama Paket tidak boleh kosong");

            return;
        }

        int durasi;
        int harga;

        try{

            durasi = Integer.parseInt(txtDurasi.getText());

            harga = Integer.parseInt(txtHarga.getText());

        }catch(NumberFormatException e){

            JOptionPane.showMessageDialog(this, "Durasi dan Harga harus angka");

            return;

        }

        PaketRental paket = new PaketRental();

        paket.setNamaPaket(txtNamaPaket.getText());

        paket.setDurasiJam(durasi);

        paket.setHargaPaket(harga);

        boolean sukses = controller.tambahData(paket);

        if(sukses){

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");

            tampilTabel();

            resetForm();

        }else{

            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan");

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(idPaketTerpilih == 0){

            JOptionPane.showMessageDialog(this,"Pilih data terlebih dahulu");

            return;

        }

        int durasi;
        int harga;

        try{

            durasi = Integer.parseInt(txtDurasi.getText());

            harga = Integer.parseInt(txtHarga.getText());

        }catch(NumberFormatException e){

            JOptionPane.showMessageDialog(this,"Durasi dan Harga harus angka");

            return;

        }

        PaketRental paket = new PaketRental();

        paket.setIdPaket(idPaketTerpilih);

        paket.setNamaPaket(txtNamaPaket.getText());

        paket.setDurasiJam(durasi);

        paket.setHargaPaket(harga);

        boolean sukses = controller.updateData(paket);

        if(sukses){

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

            tampilTabel();

            resetForm();

        }else{

            JOptionPane.showMessageDialog(this,"Data gagal diupdate");

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if(idPaketTerpilih == 0){

            JOptionPane.showMessageDialog(this,"Pilih data terlebih dahulu");

            return;

        }

        int jawab =
                JOptionPane.showConfirmDialog(
                        this,
                        "Yakin ingin menghapus data?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION
                );

        if(jawab == JOptionPane.YES_OPTION){

            boolean sukses = controller.hapusData(idPaketTerpilih);

            if(sukses){

                JOptionPane.showMessageDialog(this,"Data berhasil dihapus");

                tampilTabel();

                resetForm();

            }else{

                JOptionPane.showMessageDialog(this,"Data gagal dihapus");

            }

        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblPaketRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaketRentalMouseClicked
        int baris = tblPaketRental.getSelectedRow();

        idPaketTerpilih = Integer.parseInt(
                tblPaketRental.getValueAt(baris, 0).toString()
        );

        txtNamaPaket.setText(
                tblPaketRental.getValueAt(baris, 1).toString()
        );

        txtDurasi.setText(
                tblPaketRental.getValueAt(baris, 2).toString()
        );

        txtHarga.setText(
                tblPaketRental.getValueAt(baris, 3).toString()
        );
    }//GEN-LAST:event_tblPaketRentalMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        Dashboard dashboard = new Dashboard();

        dashboard.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaketRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaketRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaketRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaketRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaketRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDurasi;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblPaketRental;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaPaket;
    // End of variables declaration//GEN-END:variables
}
